### ISSUE TITLE
Encoding issue in Windows

### ISSUE THREAD

**Issue by shellster** [gpodder/gpodder-core#18]
Running gpo (gpodder-core) from command line results in an encoding error.  The quick fix was to run 
`chcp 65001` to enable Unicode in cmd.exe before running it.

here's the output without the above command:

```
2016-06-02 15:42:17,379 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "gpo", line 1236, in <module>
    cli._shell()
  File "gpo", line 1092, in _shell
    """ % gpodder.__dict__).splitlines()))
  File "gpo", line 183, in out
    print(*args, **kwargs)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xa9' in position 67: character maps to <undefined>
```

**Comment by Keeper-of-the-Keys** [comment]
Closed due to age, it could be this is still applicable.
