### ISSUE TITLE
Invalid keyword argument 'season'

### ISSUE THREAD

**Issue by drmikecrowe** [gpodder/gpodder-core#46]
Feed changes appear to break the code.  

Steps to reproduce:

```sh
$ pip install -r requirements.txt
$ bin/gpo

gpo> subscribe https://feeds.megaphone.fm/sciencevs sciencevs
```

Results:

```log
Subscribing to https://feeds.megaphone.fm/sciencevs                       [FAIL]
bin/gpo:382: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn('Cannot subscribe: %s', e, exc_info=True)
2023-03-25 08:41:52,432 [gpo] WARNING: Cannot subscribe: "Invalid keyword argument(s): {'season'}"
Traceback (most recent call last):
  File "bin/gpo", line 366, in subscribe
    podcast = self._get_podcast(url, create=True)
  File "bin/gpo", line 337, in _get_podcast
    return self._model.load_podcast(url, create=True)
  File "/tmp/gpodder-core/src/gpodder/model.py", line 998, in load_podcast
    return self.PodcastClass.load_(self, url, create, authentication_tokens)
  File "/tmp/gpodder-core/src/gpodder/model.py", line 666, in load_
    tmp.update()
  File "/tmp/gpodder-core/src/gpodder/model.py", line 793, in update
    self._consume_custom_feed(result)
  File "/tmp/gpodder-core/src/gpodder/model.py", line 734, in _consume_custom_feed
    new_episodes, seen_guids = custom_feed.get_new_episodes(self)
  File "/tmp/gpodder-core/src/gpodder/plugins/podcast.py", line 153, in get_new_episodes
    episode = channel.episode_factory(episode_dict.items())
  File "/tmp/gpodder-core/src/gpodder/model.py", line 698, in episode_factory
    return self.EpisodeClass(self, **dict(iterable))
  File "/home/mcrowe/.local/lib/python3.8/site-packages/minidb.py", line 703, in model_init
    raise KeyError('Invalid keyword argument(s): %r' % unmatched_kwargs)
KeyError: "Invalid keyword argument(s): {'season'}"
"Invalid keyword argument(s): {'season'}"
```

**Comment by thp** [comment]
Are all dependencies up to date? (`pip install --upgrade`)
